### ISSUE TITLE
Refine border not working in latest CPU unstall

### ISSUE THREAD

**Issue by tyremmers** [cnr-isti-vclab/TagLab#101]
Hi, 
I have recently installed the CPU version and the refine border function is not working anymore.
The python console returns:

gaussian() got an unexpected keyword argument 'multichannel'

It would be great to be able to use the refine tool again as it is one of the most valuable tool.

Thank you for your time!

**Comment by maxcorsini** [comment]
Hi, it is not clear what happened here. What is your Python version and your OS ?

**Comment by maxcorsini** [comment]
Hi,

this is a problem raised with the new version of skimage. It will be fixed in the next release of TagLab. 
For the moment, a solution is to replace in the file coraline.py (line 44) multichannel=False with channel_axis=None.

Let me know if this works.

**Comment by tyremmers** [comment]
It worked!

Thank you so much for the quick fix :)
