### ISSUE TITLE
Installation Issues: Visiual Studio 

### ISSUE THREAD

**Issue by cebardin** [cnr-isti-vclab/TagLab#107]
Hello, when I try to download TagLab I get an error when installing the dependencies. Specifically the error comes when " Preparing wheel metadata.." 
I believe the issue is with Visual Studio. I have downloaded the redistributable and build tools. Which components/packages do I need to have specifically installed for visual studio to correctly support TagLab?

Thank you!

**Comment by alemuntoni** [comment]
Hi, you just need the last vc redist package installed, that you can find [here](https://aka.ms/vs/17/release/vc_redist.x64.exe).

**Comment by cebardin** [comment]
Hi I already have that installed so that is not the issue. Is there anything else you could think of? I have TagLab working on two other machines and from what I can tell all the settings and dependencies are the same.

**Comment by maxcorsini** [comment]
Hi, 

please, post here the error so that we can try to understand the reason.

Best,

**Comment by cebardin** [comment]
Hi,
I ended up not needing to set up that specific machine so problem solved for now. Thanks!
