### ISSUE TITLE
install.py issue 

### ISSUE THREAD

**Issue by ewrubin** [cnr-isti-vclab/TagLab#116]
Hi, I am trying to install TaqLab 
I encountered an error. I am pasting my commands below.
Can someone tell me what I am doing wrong. 

eweli@DESKTOP-OSRNAUL MINGW64 ~
$ python3 --version
Python 3.11.5

eweli@DESKTOP-OSRNAUL MINGW64 ~
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Fri_Dec_17_18:28:54_Pacific_Standard_Time_2021
Cuda compilation tools, release 11.6, V11.6.55
Build cuda_11.6.r11.6/compiler.30794723_0

eweli@DESKTOP-OSRNAUL MINGW64 ~
$ pwd
/c/Users/eweli

eweli@DESKTOP-OSRNAUL MINGW64 ~
$ mkdir taqlab

eweli@DESKTOP-OSRNAUL MINGW64 ~
$ cd taqlab/

eweli@DESKTOP-OSRNAUL MINGW64 ~/taqlab
$ git clone https://github.com/cnr-isti-vclab/TagLab.git
Cloning into 'TagLab'...
remote: Enumerating objects: 7675, done.
remote: Counting objects: 100% (900/900), done.
remote: Compressing objects: 100% (350/350), done.
remote: Total 7675 (delta 596), reused 818 (delta 533), pack-reused 6775
Receiving objects: 100% (7675/7675), 321.97 MiB | 1.69 MiB/s, done.
Resolving deltas: 100% (4885/4885), done.
Updating files: 100% (270/270), done.

eweli@DESKTOP-OSRNAUL MINGW64 ~/taqlab
$ cd TagLab

eweli@DESKTOP-OSRNAUL MINGW64 ~/taqlab/TagLab (main)
$ ls
LICENSE         config.json      docs/       models/          source/
README.md       coraline/        fonts/      prova.json       update.py
TAGLAB_VERSION  dependencies.md  icons/      sampleProjects/
TagLab.py*      dictionaries/    install.py  screenshot.jpg

eweli@DESKTOP-OSRNAUL MINGW64 ~/taqlab/TagLab (main)
$ python3 install.py
Traceback (most recent call last):
  File "C:\Users\eweli\taqlab\TagLab\install.py", line 16, in <module>
    raise Exception("Python " + sys.version_info[0] + "." + sys.version_info[1] + " not supported. 
    
    Please see https://github.com/cnr-isti-vclab/TagLab/wiki/Install-TagLab")
                    ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "int") to str

**Comment by Jordan-Pierce** [comment]
You're trying to install with python 3.11, but the script won't allow you to install dependencies unless you're using python 3.8 - 3.10
