### ISSUE TITLE
Problem with Osgeo when instaling TagLab

### ISSUE THREAD

**Issue by nirivas** [cnr-isti-vclab/TagLab#127]
I keep getting this error when trying to install taglab.  I am using Python 3.9.13 which works on another computer. Any ideas on how I can fix?

Traceback (most recent call last):
  File "C:\TagLab-main\install.py", line 275, in <module>
    gdal_is_installed = importutil.find_spec("osgeo.gdal")
  File "C:\Users\vbautist\AppData\Local\Programs\Python\Python39\lib\importlib\util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
ModuleNotFoundError: No module named 'osgeo'

**Comment by Jordan-Pierce** [comment]
Hi @nirivas, [see this discussion link](https://github.com/cnr-isti-vclab/TagLab/discussions/118), it may be of use. I found it was easier to install GDAL and Rasterio (applicable versions) before running the TagLab script.

**Comment by nirivas** [comment]
It worked! Thanks, I had tried installing separately but most likely the wrong version. I appreciate it!
