### ISSUE TITLE
4-Clicks segmentation

### ISSUE THREAD

**Issue by tyremmers** [cnr-isti-vclab/TagLab#14]
Hi, 

I am interested in your tool to automate coral classification and it think that it is a very useful and very promising tool. I have limited experience in programming so I hope that my question is not too obvious. I was able to install and run TagLab on my computer but when I tried the 4-click segmentation tool the program shut down. It seems to be working at the start but when I do the last click it freeze for a couple of seconds and then shut down. I have read in the document that if the "Network's weight" is not properly placed in the modules folder the tool wouldn't work. So my question is, is my problem linked to the issue above or something else? and if it is how do I fix it? I have tried to look for 'Network's weight" in the modules folder but I didn't find anything and I am not too sure what I am supposed to look for (sorry for my ignorance, it might be obvious but I don't know).

Thanks for your time.
Cheers,
T

**Comment by maxcorsini** [comment]
Hi, 

the filename of the network weights you mentioned is "dextr_corals.pth".  This file should be placed in the "models" folder. 
If the file is not there try to launch again the "install.py" script. This script install the missing packages and download the 
missing neural networks. 

If this does not solve your problem, send me an email with the configuration of your PC/laptop (operating system, graphics board, RAM, etc). 

Cheers
Massimiliano

**Comment by tyremmers** [comment]
Hi Massimiliano,

Thank you so much for your help, I was able to fix my issue and the tool is
now working.

I was wondering if it was possible to add some georeference point or change
the XY coordinate of the image to match the location using WGS84
coordinates?
When I export the shapefile it doesn't seem to match with the location of
the geotiff I had imported in TagLab. I don't know if that's a
functionality already but it would be great to be able to set the XY
starting point.

Thanks again for your time and for developing the tool. It will be very
useful for our research.

Kind regards,
Tiny

**Comment by Miguel-Figuerola** [comment]
Hello @maxcorsini,

Thanks a lot for the follow-up. I have installed TagLab 2022.04.21. When I try to use the 4-click segmentation tool I use the shift+left mouse and the tool overlays 4 red x marks in the map. When I click the fourth, the program stalls and then shuts down. I get this in the python console before the program shuts down: 
![image](https://user-images.githubusercontent.com/78092491/181313224-6a8b7acf-2b5c-4c1b-85da-fcd58e45e6d6.png)

**Comment by Carol-Symbiomics** [comment]
![image](https://user-images.githubusercontent.com/22328380/211541598-d8db93d6-4dda-4dc3-a048-ad78018beda2.png)

Dear Massimiliano,

Could you please let me know how to fix the problem with the "4-click segmentation tool"? Without this tool I'm having to draw all the poligons manually, which increase the processing time exponentially.

Please help me!

**Comment by maxcorsini** [comment]
Dear Carol,

this problem is raised by Pytorch. It seems that something wrong happened during the download of pretrained weights used (file corrupted). You can try to uninstall and re-install pytorch writing the following commands in a shell:

1) pip uninstall torchvision 
2) Go in the TagLab folder and run again install.py (this get the right version of Pytorch according to your CUDA version)

Best,
Massimiliano

**Comment by Carol-Symbiomics** [comment]
Thank Massimiliano,

Its works now!
