### ISSUE TITLE
TagLab crashes when using 4-clicks segmentation

### ISSUE THREAD

**Issue by vickyyutinglin** [cnr-isti-vclab/TagLab#141]
Hi there,

After installing TagLab, I explored all the functions, and everything works well except for the 4-clicks segmentation feature. While I can select the four extremes, TagLab crashes after I click on the last extreme. The error message I receive is as follows:

![TagLab error](https://github.com/cnr-isti-vclab/TagLab/assets/70046772/4d289ac8-0d52-4761-9856-4ac7f11bc489)

There seems to be an issue when constructing the AI model, but I don't know what exactly this error means. I have searched for similar errors, but I still have not gotten any ideas about them. I also reinstalled Python and TagLab, and the TagLab still crashes as usual.

It seems there is an issue when constructing the AI model, but I am unsure what this error specifically means. Despite searching for similar errors, I have not found any solutions. I also reinstalled both Python and TagLab, but the issue persists.

For your reference, here are the details of my setup on Windows 11:
Python version: 3.9.13 (I downgraded from 3.10 to 3.9 to resolve the error mentioned in issue #120 )
CUDA Toolkit version: 11.6

Any assistance or suggestions to resolve this issue would be greatly appreciated!

**Comment by maxcorsini** [comment]
Sorry for the late answer. Try to launch install.py (or update.py) to re-install the networks.

**Comment by vickyyutinglin** [comment]
Hi @maxcorsini 

It works right after I re-installed it. Thank you so much!
