### ISSUE TITLE
Bug: Bricking TagLab with deleted / moved default dictionary

### ISSUE THREAD

**Issue by Jordan-Pierce** [cnr-isti-vclab/TagLab#151]
The following will brick TagLab.py
- Create a copy of your default dictionary.json
- Change the name of the copy (test.json)
- Open TagLab, go to settings, update the default dictionary to the copy (test.json)
- Close TagLab.py
- Delete test.json
- Re-open TagLab.py

self.default_dictionary is a value being read from a registry, but the events to handle if that value (path to default dictionary) is incorrect (deleted / modified) do not do what is intended (i.e., update the default dictionary to `./dictionaries/scripts.json`); instead it just bricks.

Luckily the registry stores the expected value (path) of the self.default_dictionary and outputs it to log, so the user can create a new version in the same location.

**Comment by Matt-Davies-314** [comment]
Hi Jordan, one of my colleagues is having a similar issue. Where can I find the log to find the expected path?

**Comment by Jordan-Pierce** [comment]
@Matt-Davies-314 by "log" I mean the command line console / terminal. It should complain about not finding a self.default_dictionary at the following path; that path is where you should create an updated version of your dictionary, otherwise you cannot unbrick it.

**Comment by Matt-Davies-314** [comment]
Thanks Jordan, then I guess it is not the issue. I've just seen the other thread with the 'Name' error, that's the same problem we're having.

**Comment by Jordan-Pierce** [comment]
Yep, someone else on our team is getting the same issue. The `Name` issue is that the default dictionary being used when opening TagLab doesn't have a `Name` key in the JSON file, which is why it's throwing an error. But, I'm not sure why it's happening. Will share any fixes if we find them
