### ISSUE TITLE
Taglab error + crash when importing shapefile

### ISSUE THREAD

**Issue by gracef-coral** [cnr-isti-vclab/TagLab#171]
Hi all,

Since successfully upgrading to version 2024.11.28 TagLab now crashes when I import shapefiles, leaving the following error message in the prompt:

```
Traceback` (most recent call last):
  File "C:\Users\gfrank\Documents\TagLab-main\taglab.py", line 4468, in importShapefile
    self.attribute_widget = QtAttributeWidget(data)
                            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gfrank\Documents\TagLab-main\source\QtShapefileAttributeWidget.py", line 122, in __init__
    self.fields_layout.addWidget(chkBox, i / FIELDS_FOR_ROW, i % FIELDS_FOR_ROW)
TypeError: arguments did not match any overloaded call:
  addWidget(self, w: Optional[QWidget]): too many arguments
  addWidget(self, a0: Optional[QWidget], row: int, column: int, alignment: Union[Qt.Alignment, Qt.AlignmentFlag] = Qt.Alignment()): argument 2 has unexpected type 'float'
  addWidget(self, a0: Optional[QWidget], row: int, column: int, rowSpan: int, columnSpan: int, alignment: Union[Qt.Alignment, Qt.AlignmentFlag] = Qt.Alignment()): argument 2 has unexpected type 'float'
```

As a test, I created a new shapefile, exported it and then imported it successfully without a crash - which makes me worry it's a fault with the older shapefiles. All other functions are working fine, I'm using Python v3.11.10

Any help appreciated. Thanks,
Grace

**Comment by maxcorsini** [comment]
I have checked. This is a bug caused by the new Python version. Now, it is fixed. 

Thank you to point out this problem!

**Comment by gracef-coral** [comment]
Thank you! I very much appreciate your speedy and excellent work on TagLab, I can confirm that it works great for me now.
