### ISSUE TITLE
Error importing label images

### ISSUE THREAD

**Issue by mlopezp** [cnr-isti-vclab/TagLab#27]
Before using TagLab we were manually tracing colonies using photoshop. I was testing importing these label images into TagLab so we don’t have to redo the work that we have already done, and possibly use these to create the training set for our monitoring sites. I have tried exporting the image labels as both png and jpg but the program crashes with error:

```
File "TagLab.py", line 3168, in importLabelMap
    created_blobs = self.activeviewer.annotations.import_label_map(filename, self.project.labels, self.activeviewer.img_map.width(),
  File "C:\Program Files\TagLab-main\source\Annotation.py", line 495, in import_label_map
    c = label.fill
AttributeError: 'str' object has no attribute ‘fill'
```

TagLab: 0.7
Windows: 10 Enterprise
Python: 3.8.10
nvcc: 11.3.58

**Comment by maxcorsini** [comment]
This is a known bug introduced by the functionalities related to having an editable labels dictionary. 

For the moment, fix it by manually replacing the following code:

                for label in labels_dictionary.keys():
                    c = label.fill
                    if c[0] == color[0] and c[1] == color[1] and c[2] == color[2]:
                        blob.class_name = label.name
                        break

with:

                for key in labels_dictionary.keys():
                    c = labels_dictionary[key].fill
                    if c[0] == color[0] and c[1] == color[1] and c[2] == color[2]:
                        blob.class_name = labels_dictionary[key].name
                        break

in the annotation.py file.

Best regards

**Comment by mlopezp** [comment]
Great! 
Thank you for the quick response. That worked.
The changes with the label dictionary seem exciting but definitely brought some problems. 
I will let you know if I run into any more issues. 
Best regards
