### ISSUE TITLE
4-click and Positive/Negative segmentation not working since v2022.02.24

### ISSUE THREAD

**Issue by cappelletto** [cnr-isti-vclab/TagLab#32]
After updating from [TagLab v2022.02.13](https://github.com/cnr-isti-vclab/TagLab/releases/tag/v2022.02.13) to [TagLab v2022.02.24](https://github.com/cnr-isti-vclab/TagLab/releases/tag/v2022.02.24) the click based segmentation stopped working. GUI still switches between tools but no segmentation is performed. 
Also tested with currently latest version [TagLab v2022.02.25](https://github.com/cnr-isti-vclab/TagLab/releases/tag/v2022.02.25), with same behaviour. Fixed by just rolling back to the previously working version.

Please let me know if you need more build/system info.

**Comment by maxcorsini** [comment]
From the version v2022.02.24 the 4-clicks tool require that you hold on Shift together with the left mouse button to assign a point. The same for the positive-negative clicks. We did this change to make the usage of the two tools uniform. 
In the next days we will update the documentation to address this and other changes.

**Comment by cappelletto** [comment]
Great, I will update again to the latest version.
I assume that is a hard-coded interface behaviour change, rather than a configuration level one. I mention this as the previous behaviour looked more touch-compatible.

Thanks for this great tool.
