### ISSUE TITLE
Swapped color predictions

### ISSUE THREAD

**Issue by AlbertBarreiro** [cnr-isti-vclab/TagLab#46]
Hello,

After training a network you can visualize some predictions before saving the model.
The issue is regarding the predictions . The segmentations are okay but the colors are interchanged.

I would say that the issue is because `class_names = list(self.dict_target)` is not rearranging the classes as you would like to. It's in the coral_dataset.py.

This happened in the 2022.02.25 version.

**Comment by maxcorsini** [comment]
Hello,

yes, there were inconsistencies problem in the label dictionary.  Such inconsistencies have been fixed recently, try to use the last release.
