### ISSUE TITLE
Windows DLL Load Failure

### ISSUE THREAD

**Issue by such-chris** [cnr-isti-vclab/TagLab#48]
I am trying to run TagLab on a brand new installation of Windows 10 running Python 3.7.9 and CUDA 10.2. I have tried removing an reinstalling all packages to no avail. Install.py runs fine. When running TagLab.py I get:

Traceback (most recent call last):
  File "TagLab.py", line 34, in <module>
    from PyQt5.QtCore import Qt, QSize, QMargins, QDir, QPoint, QPointF, QRectF, QTimer, pyqtSlot, pyqtSignal, QSettings, QFileInfo, QModelIndex
ImportError: DLL load failed: The specified module could not be found.

I have tried separately install PyQt5 and have tried version 5.15.7 as well as 5.15.6. I can find the .dll files for PyQt5 and have added their location to my PCs path, but I still get the DLL load failure.

Thank you,
Chris

**Comment by danielagiorgi** [comment]
Hi Chris,

Try to install the Microsoft Visual Studio Redistributable for Visual Studio 2015, 2017, 2019 and 2022 from this link:

https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170

It may solve. Let us know.

Best

**Comment by such-chris** [comment]
> 

Unfortunately I am still getting that DLL Load Failed error.

**Comment by maxcorsini** [comment]
Hi Chris,

the problem is that Python do not find the PyQt5 DLLs in the right places. Are you using conda ? Do you have other version of Qt or PyQt installed ? 

Best

**Comment by such-chris** [comment]
I am using Python 3.7.9
I am not using conda

I have only one version of PyQt5 installed via the install.py script in TagLab. It is the most recent version, 5.15.7

**Comment by such-chris** [comment]
I have update my Windows system path to include the .dll file location as well to no avail.

**Comment by such-chris** [comment]
A coworker resolved this issue for me by reinstalling everything. Apparently I did not check some boxes for adding environment variables. Thus the path was indeed incorrect. Once corrected TagLab runs.
