### ISSUE TITLE
Question: Any restriction on input mosaic size (memory or resolution)?

### ISSUE THREAD

**Issue by JordanMakesMaps** [cnr-isti-vclab/TagLab#54]
Hello,

Quick question: are there any restrictions on the size of the input raster? 

Thanks

**Comment by maxcorsini** [comment]
Hello,

the current size limit is 32767 x 32767 pixels.

Cheers

**Comment by Jordan-Pierce** [comment]
@maxcorsini is there a way to bypass this, perhaps using BigTIFF?
