### ISSUE TITLE
No module named 'pycocotools' after UPDATE

### ISSUE THREAD

**Issue by ihuanh** [cnr-isti-vclab/TagLab#58]
After the update, cannot open TagLab again and it shows up:

Traceback (most recent call last):
  File "taglab.py", line 78, in <module>
    from source.NewDataset import NewDataset
  File "C:\Users\user\OneDrive\Documents\TagLab-main\source\NewDataset.py", line 20, in <module>
    from pycocotools import mask as maskcoco
ModuleNotFoundError: No module named 'pycocotools'

Did anyone found this happening also? How can I solve this problem?

**Comment by maxcorsini** [comment]
Hi ihuanh,

yes, indeed. After the last update we need to install Microsoft Visual C++ Build Tools and re-run install.py due to a new component used to export dataset in COCO format (pycocotools). 

We will update the installation Wiki with this information.

**Comment by maxcorsini** [comment]
Unfortunately, pycocotools-windows does not support Python 3.9. But it is a good solution for people using python 3.7 and 3.8.

**Comment by mlopezp** [comment]
> @mlopezp after doing so, did you need to adjust any import statements to reflect the change from `pycocotools-windows` instead of `pycocotools`?
> 
> In addition, there's also the ability to install `pycocotools` via [Conda](https://anaconda.org/conda-forge/pycocotools), though unless you remove the `pip install pycocotools` from `install.py`, it will still attempt to install it via `pip`.
> 
> I followed @mlopezp's suggestion and so far TagLab appears to be working properly. @maxcorsini It might be worth switching to `pycocotools-windows` to avoid having to install Microsoft Visual Tools and the messiness associated.

@Jordan-Pierce I didn't have to adjust any import statements. I am running Python 3.8.10. I haven't had any issues with the installation so far.
