### ISSUE TITLE
Automatic classification crashes with Classifier Widget error

### ISSUE THREAD

**Issue by mlopezp** [cnr-isti-vclab/TagLab#62]
I am trying to train a classifier for my images. I was able to export a training data set, but when I clicked on the robot to select my classifier the program crashed with the error below. Seems like there's a problem displaying the QtClassifierWidget due to missing keys.

```
Traceback (most recent call last):
  File "taglab.py", line 4420, in selectClassifier
    self.classifierWidget = QtClassifierWidget(self.available_classifiers, parent=self)
  File "C:\Program Files\TagLab-main\source\QtClassifierWidget.py", line 82, in __init__
    self.editClasses = QLineEdit(self.classes2str(classifiers[0]["Classes"]))
  File "C:\Program Files\TagLab-main\source\QtClassifierWidget.py", line 329, in classes2str
    for key in classes_dict.keys():
AttributeError: 'list' object has no attribute 'keys'
```

**Comment by mlopezp** [comment]
Hi Massimiliano,
Here’s my config file.
Hope it helps.

Cheers,
Mauricio López

**Comment by maxcorsini** [comment]
Hi Mauricio,

I do not see the file.  Perhaps it is not possible to attach a JSON file. If this is the problem, send me it directly to my email address. You can find it in the official TagLab web page (taglab.isti.cnr.it/team).

Cheers

**Comment by mlopezp** [comment]
Just following up here.
Your changes to the config file worked.
Thanks!
