### ISSUE TITLE
Question: Docker container in the works?

### ISSUE THREAD

**Issue by Jordan-Pierce** [cnr-isti-vclab/TagLab#64]
Hello! Really interested in using TagLab, it looks great! 

I was wondering if there are any plans to develop a Docker File for running TagLab, and then just exposing the GUI from within a running Docker container? This might help with installation issues for users using different environments.

**Comment by maxcorsini** [comment]
Hi Jordan, 

At the moment we have no plan to develop a Docker for TagLab but we are preparing a PIP package to make the installation of TagLab easier. 

Best

**Comment by jebyrnes** [comment]
I see this was from last year - did either a docker container or a pip package every happen?

**Comment by kikislater** [comment]
Completed ? Where is the Dockerfile ?

**Comment by Jordan-Pierce** [comment]
> Hi Jordan,
> 
> At the moment we have no plan to develop a Docker for TagLab **but we are preparing a PIP package to make the installation of TagLab easier**.
> 
> Best

A PIP package is in the works.
