### ISSUE TITLE
Issues with Shapely? I got you.

### ISSUE THREAD

**Issue by JordanMakesMaps** [cnr-isti-vclab/TagLab#7]
If you run into an issue with Shapely after downloading and installing all of the requirements, uninstall the version of Shapely that you installed with the other packages using pip. Then install it with conda instead. If everything else installed correctly, you should be good.

Cheers.

**Comment by maxcorsini** [comment]
Thank you very much for this suggestion. Which platform do you use?

**Comment by JordanMakesMaps** [comment]
Windows 10, using Conda 4.6 and installed on a fresh new environment.

**Comment by maxcorsini** [comment]
Perfect. And thank you again!
