### ISSUE TITLE
Installation issue: AttributeError: module 'numpy' has no attribute 'int'

### ISSUE THREAD

**Issue by ihuanh** [cnr-isti-vclab/TagLab#75]
Another installation issue found.

Installation success, update for double check success. However after running the Taglab for the first time, the following comes out:

TagLab 2022.11.3
Traceback (most recent call last):
  File "taglab.py", line 4704, in <module>
    tool = TagLab()
  File "taglab.py", line 437, in __init__
    self.labels_widget.setLabels(self.project, None)
  File "...source\QtTableLabel.py", line 240, in setLabels
    self.data = project.create_labels_table(self.activeImg)
  File "...source\Project.py", line 492, in create_labels_table
    'Visibility': np.zeros(len(self.labels), dtype=np.int),
  File "...AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'

Window 11
Python 3.8.0
NVCC  11.6

Anyway I can fix this issue?

**Comment by maxcorsini** [comment]
Let's try to update your numpy package writing in a shell: 

pip install numpy --upgrade

**Comment by maxcorsini** [comment]
There is a problem with the numpy package. 

I have found that sometimes may help to uninstall and then reinstall numpy:

pip uninstall -y numpy
pip install numpy

Others solved the problem by reinstalling with numpy also another package called setuptools:

pip uninstall -y numpy
pip uninstall -y setuptools
pip install setuptools
pip install numpy

I suggest trying the second solution.

**Comment by KayB-Swimmin** [comment]
Hi, 

I'm having this issue as well. I also tried the solutions provided and still failed.

**Comment by KayB-Swimmin** [comment]
I was able to fix this by installing an older version of numpy.

**Comment by maxcorsini** [comment]
Right! Recently, other users notified us that this bug is related to a new version of numpy (1.24), Install an older version, for example 1.23 writing in a shell the command pip install --force-reinstall numpy==1.23, solve the problem.
